### ISSUE TITLE
Won't run with Keypirinha 2.24

### ISSUE THREAD

**Issue by unpoetical** [samusaran/keypirinha-epiclauncher#1]
Getting errors:

```
20:36:44.121 ** ERROR: Error from EpicLauncher.EpicLauncher.on_catalog: <class 'KeyError'>: ('AppID',)
Traceback (most recent call last):
  File "E:\Program Files\Keypirinha\portable\Profile\InstalledPackages\EpicLauncher.keypirinha-package\epiclauncher.py", line 35, in on_catalog
  File "E:\Program Files\Keypirinha\portable\Profile\InstalledPackages\EpicLauncher.keypirinha-package\epiclauncher.py", line 94, in get_applist
```

There is no AppId in C:\ProgramData\Epic\UnrealEngineLauncher\LauncherInstalled.dat.   Also the AppName seems to be garbage, instead take the last element of the path as the app name to display in keypirinha.

Changed line 94 to 

```
            app = InstalledApp(entry["InstallLocation"], os.path.basename(entry["InstallLocation"]), "NOID", entry["AppVersion"], None)
```

**Comment by SturmB** [comment]
Having the exact same issue. Removing the package until this is fixed.

**Comment by samusaran** [comment]
#3 seems to have fixed the issue. I'm on vacation so I can't test it thoroughly, but I will when I get back
